allowBuilds:
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  unrs-resolver: set this to true or false
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@clerk/clerk-js@6.29.0'
  - '@clerk/expo@4.2.8'
  - '@clerk/react@6.14.2'
  - '@clerk/shared@4.29.0'
